# Generated by Django 3.2.16 on 2024-06-12 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.PositiveIntegerField(verbose_name='Внешний ID клиента')),
                ('name', models.TextField(verbose_name='Имя клиента')),
                ('date_added', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата первого подключения')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
                'ordering': ('-date_added',),
            },
        ),
        migrations.CreateModel(
            name='Subscriptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата первого подключения')),
                ('amount_of_days', models.DurationField(verbose_name='Количество дней в подписке')),
                ('product', models.CharField(max_length=256, verbose_name='Продукт в подписке')),
                ('current_status', models.CharField(max_length=256, verbose_name='Активность подписки')),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client', to='business_logic.clients')),
            ],
            options={
                'verbose_name': 'Подписка',
                'verbose_name_plural': 'Подписки',
                'ordering': ('-start_date',),
            },
        ),
    ]
