# Generated by Django 3.2.16 on 2024-06-12 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_logic', '0002_alter_subscriptions_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptions',
            name='amount_of_days',
            field=models.SmallIntegerField(verbose_name='Количество дней в подписке'),
        ),
    ]
