# Generated by Django 3.2.16 on 2024-06-15 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business_logic', '0003_alter_subscriptions_amount_of_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptions',
            name='expire_date',
            field=models.DateField(db_index=True, null=True, verbose_name='Дата окончания подписки'),
        ),
        migrations.AlterField(
            model_name='subscriptions',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client', to='business_logic.clients', verbose_name='Клиент'),
        ),
    ]
