# Generated by Django 3.2.16 on 2024-06-15 09:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_logic', '0004_auto_20240615_0927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptions',
            name='expire_date',
            field=models.DateField(db_index=True, default=datetime.datetime(2024, 6, 15, 9, 37, 59, 550030), verbose_name='Дата окончания подписки'),
        ),
    ]
