# Generated by Django 3.2.16 on 2024-06-15 09:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business_logic', '0005_alter_subscriptions_expire_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptions',
            name='expire_date',
            field=models.DateField(db_index=True, default=datetime.datetime(2024, 6, 15, 9, 39, 56, 157790), verbose_name='Дата окончания подписки'),
        ),
        migrations.AlterField(
            model_name='subscriptions',
            name='start_date',
            field=models.DateField(db_index=True, default=datetime.datetime(2024, 6, 15, 9, 39, 56, 157742), verbose_name='Дата первого подключения'),
        ),
    ]
