# Generated by Django 3.2.16 on 2024-06-15 10:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('business_logic', '0007_auto_20240615_0942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscriptions',
            name='expire_date',
            field=models.DateField(db_index=True, default=django.utils.timezone.now, verbose_name='Дата окончания подписки'),
        ),
        migrations.AlterField(
            model_name='subscriptions',
            name='start_date',
            field=models.DateField(db_index=True, default=django.utils.timezone.now, verbose_name='Дата первого подключения'),
        ),
    ]
